sudo: required
language: java
services:
- docker
before_install:
- mkdir /tmp/build
- docker pull qcifengineering/redbox-builder
- docker run -v /tmp/build:/build -e "CLONEPATH=https://github.com/the-fascinator/plugin-access-db.git"
  qcifengineering/redbox-builder
install: true
script: true
after_success:
- docker run -v /tmp/build:/build -e "SONATYPE_USERNAME=$SONATYPE_USERNAME" -e "SONATYPE_PASSWORD=$SONATYPE_PASSWORD"
  qcifengineering/redbox-builder /bin/bash -c "cd build/src;mvn --settings /m2_repo/travis-settings.xml
  -Dmaven.repo.local=/m2_repo -DskipTests=true deploy"
env:
  global:
  - secure: lhtL5rE8MONiRLgZ3dpMidZeT7JGnM/EgtsLWEaQOhry01TpmG3mtkkhZ6sqT7Lr2eS0I9Zi14o/7x8z9Z6O3bC2DVB7hd7qPnjRymE+5GGTNnqG6DLSpPtpT4g/zr0bN/8/xwH7rH4Qvg/w8+Pqu1f9lF3tNB99TyVnnjzCyKprcmmg6pukuUSxCru20B9QvIHzsK4EIJOkdx9n9dQD63iLe2Zq8ZkPK3lh3//aaPe3wfyyYOWhMdOR303kuyzLTrAnJO9OLPgtVtss6pPT3JcMcZZcV16cc8Vp0tqwJRgNzWFre/IinFvosdaUqMnHNG6ENUt6k6bzYt0dMjRD1FnlS3iBE/S1r35wUxwhnG59VQeMV9wAYwdXjG/dKZOldYaTJ8NAOSrworgUyc3n4teWKqeIx5jhAL7BsOaMFISlLhaCg6S0w4kKs9+ODwt1TRJ6CPQ2OdLsV0bHzP2nP15vfldxA/q7iOcvu2m59Zrj1VVc1UbgTyjRirsFLXM2CX76ySPc7f9NQ5XDSf6uR94edHbBNWWBR1FBlhRV6dw1YNXchVghE2+KbtyXDacpytoniQ0jTVnFPZVOXXsNCHTi2me/HDhQgDdhaJHqPWeJ2LLuXTclagIdSZpOHjloyPjfh55kR8CtxxVb3yLkhDTq/mm1WePG6mPhm5pQZnI=
  - secure: A1hh+xEcDNX/dGDKfqAxFPVxlpDojNS0GukWTFEaWyyzwLAtNsAhX1aCg8DzIZuH2cGjC68eB+VlU8FO+E+zbp8VIK6pgohxvlK1nm0EcCm41WF4GrQ4HDu4rux2nLc6ZyeUSWgpI7G+d3F2Sst4ZgAB0kifz3bVzdiGwvu2KxL1ZTEhbYNyzYYcz3ylEeCywK51pbEflW1dbN8SpfgjqzinlBFnZ/FqFhBu0txynQpWXo7641RznS3nUamgyPYMbf/gUZhK0RuHLf9mRHrqIchuwH9M2VOytVuhww/EVLPGyNQnNIrd6DPXSiwRExFvE7pLZ9bzzrutW1PbsrS6Jf2AZw35vB3PMixFJ/nty9XHtt526QITyV0THm3TTO5TmtPTssOLwraZmz9JcQM05/hf5INyanuZfluYb7bNYYQUEOI0cSMLj/EcY2QNr6pR5sGPylIsPD1KhlYoUUP7qBbzqvoWx9EOQjfpidDvWokLhPaN8lqOkW7zUSjY1RYk70T92qoXBRdIcqCgyL8gyDAS++tCXyU696dgpEeLaHo+lfIBMGjrzkhGn0Ywc2HveFT2aTmvrVZrGfOjlMwSRr3IEwcIVuYxAincrHlCY8Qn0Khk4jFcfACPXHIArTVGTnbvsV6fEHeVJfei4ak9slUSvbSHbl9IEu49Vl4Ca9A=
notifications:
  webhooks:
    urls:
      - http://dev.redboxresearchdata.com.au/hooks/travis
    on_success: always
    on_failure: never
    on_start: never
